### ISSUE TITLE
Still errors compiling for macOS

### ISSUE THREAD

**Issue by boonier** [TheTechnobear/Mi4Pd#11]
in reference to https://github.com/TheTechnobear/Mi4Pd/issues/8

I'm still getting the same error, here it is in full:

```
/GIT-work/Pd/Mi4Pd/mi/stmlib/dsp/dsp.h:150:33: error: invalid output constraint
      '=w' in asm
    __asm ("vsqrt.f32 %0, %1" : "=w" (result) : "w" (x) );
                                ^
1 error generated.
make[2]: *** [mi/CMakeFiles/MILib.dir/stmlib/dsp/units.cc.o] Error 1
make[1]: *** [mi/CMakeFiles/MILib.dir/all] Error 2
make: *** [all] Error 2
```

I followed all the build instructions

cmake version 3.14.1
macOS 1014.6

cheers

**Comment by shakfu** [comment]
I'm having the same error on OS X Catalina.

**Comment by TheTechnobear** [comment]
hmm, odd this occurs if the TEST macro is not defined.

I'll check this now.

------

btw: this is not related to  #8 - which was a simple user error 
I simply updated the instructions ... I didnt have to change anything ;)
