### ISSUE TITLE
get rid of checked in m_pd.h

### ISSUE THREAD

**Issue by umlaeute** [TheTechnobear/Mi4Pd#13]
`m_pd.h` really shouldn't be present in the repository, as it is tightly coupled Pd itself.
including it here, forces to support only a specific version of Pd.

Pd is (mostly?) API & ABI compatible for the last 20 years or so, but the file does change and introduces new features, some of them automatically.

related: you might consider using [pd.build](https://github.com/pierreguillot/pd.build) as the basis for your CMake project, as (I think) it wraps much of the ugliness when using CMake with Pd.

**Comment by TheTechnobear** [comment]
PD are very unlikely to break the ABI compatiblity at this stage, so it feels better to keep m_pd.h so its easier for users to compile without having to start setting a PD path. esp. as on some OS where PD is installed is variable esp. 
(e.g. on macOs we tend to have it in /Applications under the app BUT the app has version number so you cannot really just 'guess' which one to use)

**Comment by umlaeute** [comment]
you are definitely missing out on any double-precision changes, but that is of course your call to make.
