### ISSUE TITLE
grids gives error on opening

### ISSUE THREAD

**Issue by shakfu** [TheTechnobear/Mi4Pd#14]
Complains on opening that the class decl should have a GIMME.

I see that in this case it does, it's just missing a zero at the end. 

Incidentally, I've fixed this error before in my fork of the [spoitras/Pd-Grids](https://github.com/spoitras/Pd-Grids) version. Here's the commit:

https://github.com/shakfu/grids-for-pd/commit/f25fd9db9faada4333318f91d8bc436411b168da

S

**Comment by TheTechnobear** [comment]
thanks, will fix now
