### ISSUE TITLE
Error Compiling for Mac

### ISSUE THREAD

**Issue by maximosigniorini** [TheTechnobear/Mi4Pd#8]
I'm a bit of a noob in regards to compiling externals, I'm trying to compile this for OSX with Xcode and this error keeps poping up "Invalid output constraint '=w' in asm". I have already included all the files needed for the project. Any help is very much appreciated!

**Comment by TheTechnobear** [comment]
Are you using cmake ? 
As you need to use cmake to create makefiles. 
check out the documentation for cmake , it explains how to use with Xcode

**Comment by maximosigniorini** [comment]
I was skipping that part thank! I've now tried it but it still fails compiling. It seems it can't find "libMILib.a" in Build/mi/Debug/libMILib.a

**Comment by TheTechnobear** [comment]
ok, Ive updated the build instructions in the README, 
I think your trying to compile it incorrectly, you don't compile individual externals separately they are all compiled in one go

all you need to do is :

```
mkdir build 
cd build
cmake ..
make
```

note: you're not using the xcode IDE, the above will use the xcode command line tools

**Comment by maximosigniorini** [comment]
I can't thank you enough! It was easier than I thought! It is know all working thank you very much for taking the time to help me through

**Comment by TheTechnobear** [comment]
you're welcome... 
I should have had the build instructions on the readme to make it clear - so thats some progress :)
