### ISSUE TITLE
A step missing in build documentation

### ISSUE THREAD

**Issue by marko-marjanovic** [TheTechnobear/Mi4Pd#9]
Build documentation misses the following step (after cloning the repository):
`git submodule update --init`

**Comment by TheTechnobear** [comment]
that woud be try IF i was using submodules , which im not ;) 
(its true for MEC, but that includes the instruction) 

at the moment, Im not using MI as a submodule because there's a compilation..with the MI repo on some platforms, 
so I need to patch it manually to fix this issue.
